---
abstract: 'Brightcove Media API Wrapper'
author:
  - 'Maroun NAJM <mnajm@cinemoz.com>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200006, CPAN::Meta::Converter version 2.110930'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Brightcove-MAPI
requires:
  Any::Moose: 0
  JSON: 0
  LWP::Protocol::https: 6
  LWP::UserAgent: 0
  URI: 0
version: 0.1
